name: Maven

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test on JDK 16
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16

      - name: Build with Maven
        run: mvn --batch-mode verify
